import Head from 'next/head';
import {
  Container,
  Typography,
  Grid,
  Box,
  Button,
  Link as MuiLink,
} from '@mui/material';
import Image from 'next/image';
import SocialLinks from '../Components/SocialLinks';
import WelcomeImg from '../images/welcome.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Grid
          container
          direction={{ xs: 'column-reverse', md: 'row' }}
          spacing={5}
          sx={{ my: 5 }}>
          <Grid item xs={12} sm={9}>
            <Typography variant="h3" paragraph color="primary">
              Hi, I&apos;m{' '}
              <Box component="span" sx={{ color: 'secondary.main' }}>
                Edwin
              </Box>
            </Typography>
            <Typography variant="h5" paragraph>
              I am a software engineer currently focusing on bringing web
              projects to life.
            </Typography>

            <Button
              component={MuiLink}
              color="secondary"
              variant="contained"
              href="mailto:edwingl@uci.edu"
              sx={{ mt: 2 }}>
              contact
            </Button>

            <SocialLinks />
          </Grid>

          <Grid item xs={12} sm={3} sx={{ m: 'auto' }}>
            <Image src={WelcomeImg} height={250} width={220} />
          </Grid>
        </Grid>
      </Container>
    </>
  );
}
