import Head from 'next/head';
import {
  Container,
  Typography,
  Stack,
  Box,
  Button,
  Link as MuiLink,
} from '@mui/material';
import Image from 'next/image';
import SocialLinks from '../Components/SocialLinks';
import WelcomeImg from '../images/welcome.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Stack
          direction={{ xs: 'column-reverse', md: 'row' }}
          columnGap="20%"
          justifyContent="space-between"
          sx={{ py: 5 }}>
          <Box sx={{ mt: 4 }}>
            <Typography variant="h3" paragraph color="primary">
              Hi, I&apos;m{' '}
              <Box component="span" sx={{ color: 'secondary.main' }}>
                Edwin
              </Box>
            </Typography>
            <Typography variant="h5" paragraph>
              I am a software engineer currently focusing on bringing web
              projects to life.
            </Typography>

            <Button
              component={MuiLink}
              color="secondary"
              variant="contained"
              href="mailto:edwingl@uci.edu"
              sx={{ mt: 2 }}>
              contact
            </Button>

            <SocialLinks />
          </Box>

          <Image
            src={WelcomeImg}
            height={270}
            width={320}
            objectFit="contain"
          />
        </Stack>
      </Container>
    </>
  );
}
