const Projects = [
  {
    id: 1,
    name: 'DreamScholars',
    overview: 'dreamScholars.overview',
    description: 'dreamScholars.description',
    moreDetails: 'dreamScholars.moreDetails',
    techUsed: ['react', 'typescript', 'mui', 'jest', 'firebase'],
    type: 'web',
    link: 'https://dreamscholars.org/',
    mainImg: '/images/projects/dreamscholars.jpg',
    secondImg: '/images/projects/dreamscholars2.jpg',
    mainImgAltText:
      'A tablet and iphone showcasing the home page of the scholarship website',
    secondImgAltText:
      'Various views of the website displaying the filters, schoalrship page, and scholarship form',
  },
  {
    id: 2,
    name: 'Nedflix',
    overview: 'nedflix.overview',
    description: 'nedflix.description',
    moreDetails: 'nedflix.moreDetails',
    techUsed: ['react', 'js', 'css', 'firebase'],
    type: 'web',
    link: 'https://nedflix-2c9c4.web.app/',
    mainImg: '/images/projects/nedflix.jpg',
    secondImg: '/images/projects/nedflix2.jpg',
    mainImgAltText:
      'A tablet and iphone displaying a movie banner followed by movie posters to explore',
    secondImgAltText:
      'Various screens displaying the my list, sign-in, search and movie page',
  },
  {
    id: 3,
    name: 'Casa Magda',
    overview: 'casaMagda.overview',
    description: 'casaMagda.description',
    moreDetails: 'casaMagda.moreDetails',
    techUsed: ['js', 'jquery', 'html', 'css', 'figma'],
    type: 'web',
    link: 'https://casamagda-b1768.web.app/',
    mainImg: '/images/projects/casamagda.jpg',
    secondImg: '/images/projects/casamagda2.jpg',
    mainImgAltText:
      'An iphone and mackbook displaying the landing page of the website',
    secondImgAltText:
      '2 screens showing the landing page, about us, our services, locations and contact form sections of the website',
  },
  {
    id: 4,
    name: 'TRAPD',
    overview: 'trapd.overview',
    description: 'trapd.description',
    moreDetails: 'trapd.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://play.google.com/store/apps/details?id=com.Edlo.Trapd&hl=en_US&gl=US',
    mainImg: '/images/projects/trapd.jpg',
    secondImg: '/images/projects/trapd2.jpg',
    mainImgAltText: 'A mobile phone showcasing the main menu of the TRAPD game',
    secondImgAltText:
      'Multiple phones displaying the shop, creatures, highscores, game over and gameplay screens',
  },
  {
    id: 5,
    name: 'Pacific Marine App',
    overview: 'pacificMarineApp.overview',
    description: 'pacificMarineApp.description',
    moreDetails: 'pacificMarineApp.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://github.com/edwingl10/Pacific-Marine-App',
    mainImg: '/images/projects/pmmc.jpg',
    secondImg: '/images/projects/pmmc2.jpg',
    mainImgAltText:
      'A tablet showing a seal with an inventory of tools below it',
    secondImgAltText:
      'Multiple tablets showing different seals being treated and rehabilited by the tools in the inventory',
  },
  {
    id: 6,
    name: 'Party Bash Companion',
    overview: 'partyBash.overview',
    description: 'partyBash.description',
    moreDetails: 'partyBash.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://github.com/edwingl10/PartyBashCompanion',
    mainImg: '/images/projects/partybash.jpg',
    secondImg: '/images/projects/partybash2.jpg',
    mainImgAltText:
      'A phone displaying the menu of the game, with 2 players ready to play',
    secondImgAltText:
      'Numerous phones showcasing the coins, shop, wheel, challenge and dice roll screens',
  },
  {
    id: 7,
    name: 'Search-ED',
    overview: 'searchEd.overview',
    description: 'searchEd.description',
    moreDetails: 'searchEd.moreDetails',
    techUsed: ['python', 'mongodb', 'pycharm'],
    type: 'other',
    link: 'https://github.com/edwingl10/Search-ED',
    mainImg: '/images/projects/search-ed.jpg',
    secondImg: '/images/projects/search-ed2.jpg',
    mainImgAltText:
      'A laptop displaying a split screen with 2 Python code files open',
    secondImgAltText:
      '2 monitors displaying the search field followed by the results and a mongodb database',
  },
  {
    id: 8,
    name: 'Fault Localization',
    overview: 'faultLocalization.overview',
    description: 'faultLocalization.description',
    moreDetails: 'faultLocalization.moreDetails',
    techUsed: ['python', 'terminal', 'pycharm'],
    type: 'other',
    link: 'https://github.com/edwingl10/fault-localization',
    mainImg: '/images/projects/fault-local.jpg',
    secondImg: '/images/projects/fault-local2.jpg',
    mainImgAltText:
      'A laptop displaying a split screen with 2 Python code files open',
    secondImgAltText:
      'A monitor with a split screen of a csv file with scores and a code file open next to it',
  },
  {
    id: 9,
    name: 'Operating System GUI',
    overview: 'operatingSystemGui.overview',
    description: 'operatingSystemGui.description',
    moreDetails: 'operatingSystemGui.moreDetails',
    techUsed: ['java', 'eclipse'],
    type: 'other',
    link: 'https://github.com/edwingl10/OSGui',
    mainImg: '/images/projects/osgui.jpg',
    secondImg: '/images/projects/osgui2.jpg',
    mainImgAltText:
      'A laptop displaying a split screen with 2 Java code files open',
    secondImgAltText:
      'A monitor with a python file open and q GUI next to it showcasing the users, disks, printers and directory manager status',
  },
  {
    id: 10,
    name: 'Info Weather',
    overview: 'infoWeather.overview',
    description: 'infoWeather.description',
    moreDetails: 'infoWeather.moreDetails',
    techUsed: ['react', 'js', 'css'],
    type: 'web',
    link: 'https://edwingl10.github.io/infoweather/',
    mainImg: '/images/projects/infoweather.jpg',
    secondImg: '/images/projects/infoweather2.jpg',
    mainImgAltText: 'A phone and tablet displaying weather information',
    secondImgAltText: 'A website screen of weather information',
  },
];

export default Projects;
