const Projects = [
  {
    id: 'dreamscholars',
    name: 'DreamScholars',
    overview: 'dreamScholars.overview',
    description: 'dreamScholars.description',
    moreDetails: 'dreamScholars.moreDetails',
    techUsed: ['react', 'typescript', 'mui', 'jest', 'firebase'],
    type: 'web',
    link: 'https://dreamscholars.org/',
    mainImg: '/images/projects/dreamscholars.jpg',
    secondImg: '/images/projects/dreamscholars2.jpg',
    mainImgAltText: 'dreamScholars.mainAltText',
    secondImgAltText: 'dreamScholars.secondaryAltText',
  },
  {
    id: 'nedflix',
    name: 'Nedflix',
    overview: 'nedflix.overview',
    description: 'nedflix.description',
    moreDetails: 'nedflix.moreDetails',
    techUsed: ['react', 'js', 'css', 'firebase'],
    type: 'web',
    link: 'https://nedflix-2c9c4.web.app/',
    mainImg: '/images/projects/nedflix.jpg',
    secondImg: '/images/projects/nedflix2.jpg',
    mainImgAltText: 'nedflix.mainAltText',
    secondImgAltText: 'nedflix.secondaryAltText',
  },
  {
    id: 'casa-magda',
    name: 'Casa Magda',
    overview: 'casaMagda.overview',
    description: 'casaMagda.description',
    moreDetails: 'casaMagda.moreDetails',
    techUsed: ['js', 'jquery', 'html', 'css', 'figma'],
    type: 'web',
    link: 'https://casamagda-b1768.web.app/',
    mainImg: '/images/projects/casamagda.jpg',
    secondImg: '/images/projects/casamagda2.jpg',
    mainImgAltText: 'casaMagda.mainAltText',
    secondImgAltText: 'casaMagda.secondaryAltText',
  },
  {
    id: 'trapd',
    name: 'TRAPD',
    overview: 'trapd.overview',
    description: 'trapd.description',
    moreDetails: 'trapd.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://play.google.com/store/apps/details?id=com.Edlo.Trapd&hl=en_US&gl=US',
    mainImg: '/images/projects/trapd.jpg',
    secondImg: '/images/projects/trapd2.jpg',
    mainImgAltText: 'trapd.mainAltText',
    secondImgAltText: 'trapd.secondaryAltText',
  },
  {
    id: 'pacific-marine-app',
    name: 'Pacific Marine App',
    overview: 'pacificMarineApp.overview',
    description: 'pacificMarineApp.description',
    moreDetails: 'pacificMarineApp.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://github.com/edwingl10/Pacific-Marine-App',
    mainImg: '/images/projects/pmmc.jpg',
    secondImg: '/images/projects/pmmc2.jpg',
    mainImgAltText: 'pacificMarineApp.mainAltText',
    secondImgAltText: 'pacificMarineApp.secondaryAltText',
  },
  {
    id: 'party-bash-companion',
    name: 'Party Bash Companion',
    overview: 'partyBash.overview',
    description: 'partyBash.description',
    moreDetails: 'partyBash.moreDetails',
    techUsed: ['unity', 'csharp', 'illustrator', 'photoshop'],
    type: 'game',
    link: 'https://github.com/edwingl10/PartyBashCompanion',
    mainImg: '/images/projects/partybash.jpg',
    secondImg: '/images/projects/partybash2.jpg',
    mainImgAltText: 'partyBash.mainAltText',
    secondImgAltText: 'partyBash.secondaryAltText',
  },
  {
    id: 'search-ed',
    name: 'Search-ED',
    overview: 'searchEd.overview',
    description: 'searchEd.description',
    moreDetails: 'searchEd.moreDetails',
    techUsed: ['python', 'mongodb', 'pycharm'],
    type: 'other',
    link: 'https://github.com/edwingl10/Search-ED',
    mainImg: '/images/projects/search-ed.jpg',
    secondImg: '/images/projects/search-ed2.jpg',
    mainImgAltText: 'searchEd.mainAltText',
    secondImgAltText: 'searchEd.secondaryAltText',
  },
  {
    id: 'fault-localization',
    name: 'Fault Localization',
    overview: 'faultLocalization.overview',
    description: 'faultLocalization.description',
    moreDetails: 'faultLocalization.moreDetails',
    techUsed: ['python', 'terminal', 'pycharm'],
    type: 'other',
    link: 'https://github.com/edwingl10/fault-localization',
    mainImg: '/images/projects/fault-local.jpg',
    secondImg: '/images/projects/fault-local2.jpg',
    mainImgAltText: 'faultLocalization.mainAltText',
    secondImgAltText: 'faultLocalization.secondaryAltText',
  },
  {
    id: 'operating-system-gui',
    name: 'Operating System GUI',
    overview: 'operatingSystemGui.overview',
    description: 'operatingSystemGui.description',
    moreDetails: 'operatingSystemGui.moreDetails',
    techUsed: ['java', 'eclipse'],
    type: 'other',
    link: 'https://github.com/edwingl10/OSGui',
    mainImg: '/images/projects/osgui.jpg',
    secondImg: '/images/projects/osgui2.jpg',
    mainImgAltText: 'operatingSystemGui.mainAltText',
    secondImgAltText: 'operatingSystemGui.secondaryAltText',
  },
  {
    id: 'info-weather',
    name: 'Info Weather',
    overview: 'infoWeather.overview',
    description: 'infoWeather.description',
    moreDetails: 'infoWeather.moreDetails',
    techUsed: ['react', 'js', 'css'],
    type: 'web',
    link: 'https://edwingl10.github.io/infoweather/',
    mainImg: '/images/projects/infoweather.jpg',
    secondImg: '/images/projects/infoweather2.jpg',
    mainImgAltText: 'infoWeather.mainAltText',
    secondImgAltText: 'infoWeather.secondaryAltText',
  },
];

export default Projects;
